stages:
  - build 
  - test
  - deploy

#variables
variables:
  MAVEN_CLI_OPTS: '-B -DskipTests'

image: maven:3.8-openjdk-17


build-frontend:
  stage: build
  image: node:22.4-alpine3.19
  tags:
    - dalfcs_docker_kvm
  script: 
    - cd Daltweets
    - npm install
    - npm run build
  artifacts:
    paths:
      - Daltweets/dist/*


build-backend: 
  stage: build
  tags:
    - dalfcs_docker_kvm
  script: 
    - cd Daltweets_backend
    - mvn $MAVEN_CLI_OPTS clean install package
  artifacts:
    paths:
      - Daltweets_backend/target/*.jar

  
test-backend:
  stage: test
  tags:
    - dalfcs_docker_kvm
  script: 
    - cd Daltweets_backend
    - mvn clean test -Dspring.profiles.active=test
  
